version: '3.4'
services:
  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: bash -c "rasa run -m 20230116-003850-median-cottage.tar.gz --enable-api --cors \"*\" --port 5006 "
    ports:
    - '5006:5006'
    public: true
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./utils:/app/utils
    command: bash -c "python -m rasa_sdk.endpoint --actions actions"
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
